### ISSUE TITLE
Rename drag.subject to drag.data?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-drag#17]
The word *subject* implies it’s the thing doing the dragging, not the thing being dragged. We could use the word *object*, but I think *data* would be better.

Or not. *Subject* is defined as “a person or thing that is being discussed, described, or dealt with.” Which could be appropriate.

**Comment by altocumulus** [comment]
When first running into *subject*, I intuitively got it right. I'd prefer *subject* over *data* or *object*.

**Comment by mbostock** [comment]
Yeah, it’s probably fine.
