### ISSUE TITLE
d3.event.sourceEvent.target in safari mobile

### ISSUE THREAD

**Issue by gshrman** [d3/d3-drag#30]
There seems to be a discrepancy between desktop browsers and safari mobile browser when calculating d3.event.sourceEvent.target during a drag event.  See example below:

https://jsfiddle.net/5ngf178o/10/

**Comment by mbostock** [comment]
Per https://www.w3.org/TR/touch-events/#touchevent-interface:

> target of type EventTarget, readonly
> The EventTarget on which the touch point started when it was first placed on the surface, even if the touch point has since moved outside the interactive area of that element.
