### ISSUE TITLE
Dispatching mousedown event with drag behaviour throws error

### ISSUE THREAD

**Issue by Mourdraug** [d3/d3-drag#37]
I wrote small [jsFiddle](https://jsfiddle.net/hx42hq7h/) to demonstrate issue. 
Dispatching 'mousedown' event on selection with drag behaviour results in TypeError: Cannot read property 'document' of undefined.

I need to add element on mousedown, and drag it along untill I release it, but since it does not exist on actual mousedown I'm trying to dispatch event after its added.

**Comment by mbostock** [comment]
You can’t use selection.dispatch to dispatch a mouse event; it dispatches custom events. It might be possible to dispatch a mouse event programmatically but you’ll need to do it using the appropriate W3C API and to populate the appropriate fields.
