### ISSUE TITLE
d3-drag doesn't work in Chrome's mobile test mode

### ISSUE THREAD

**Issue by nicolas-van** [d3/d3-drag#41]
I'm using Chrome 60.

To reproduce open the developers tools (Menu -> More Tools -> Developper Tools) then "Toggle device toolbar", then choose a device (as example: Ipad). Then open any examples for d3 drag ([like this one](https://bl.ocks.org/mbostock/c206c20294258c18832ff80d8fd395c3)).

It simply doesn't work anymore. As far as I can read d3 should support touch events, which Chrome is using to emulate its mobile test mode.

**Comment by mbostock** [comment]
The problem with the mobile device emulator is that it doesn’t pass our test for touch support: 

https://github.com/d3/d3-drag/blob/44af703e0148c120d9c1b4b66096efa41d2ee3a2/src/drag.js#L21-L23

It seems that if you enable the device emulator and then reload, the top-level window *does* pass: `"ontouchstart" in window` is true. However, the same test is false for HTML elements such as the BODY and the CANVAS, so D3 assumes that touch events are unsupported and does not register touch event listeners. (See 870498d928b79bc6c3a53912087feedf8652ffa9 #35 for context.)

Curiously enough, you also can’t assign a touch event listener using *element*.ontouchstart in the device emulator. You can however use *element*.addEventListener for *touchstart* events!

So, I consider this a bug in Chrome’s device emulator. If it’s not possible to detect whether touch may be *possible*, then we’d have to go back to always registering touch event listeners, which would then cause a passive event listener warning.

**Comment by nicolas-van** [comment]
OK. It's probably linked to the fact that touch events [are still in level 2](https://w3c.github.io/touch-events/#widl-GlobalEventHandlers-ontouchstart).

Since it's still a bit problematic, may I propose to add an option to allow overriding the autodetection ? See pull request #42 .

**Comment by mbostock** [comment]
Released *drag*.touchable in 1.2.0. Thanks!
