### ISSUE TITLE
Default drag.touchable should use navigator.maxTouchPoints, if supported?

### ISSUE THREAD

**Issue by Herst** [d3/d3-drag#47]
See https://crbug.com/392584

No idea what d3.js could or should do about it, probably do nothing and just add a note to the documentation of `drag.touchable`?

(Or use `navigator.maxTouchPoints`/`window.matchMedia("(any-pointer)")`?)

**Comment by altocumulus** [comment]
With the release of Chrome v70 this seems to have become an issue: [*"Touch handling completely broken on Chrome version 70"*](https://stackoverflow.com/questions/53231736/d3js-completely-broken-on-chrome-version-70).

**Comment by mbostock** [comment]
You can use `drag.touchable(navigator.maxTouchPoints)` or similar if you want to change how d3-drag detects support for touch.

**Comment by Herst** [comment]
Firefox followed suit: https://bugzil.la/1412485
