### ISSUE TITLE
Reaching drag event scope with ES6

### ISSUE THREAD

**Issue by nextlevelshit** [d3/d3-drag#53]
For instance I put some circles onto a SVG canvas and want them to trigger a function on a drag event.

**Setup:**
- TypeScript/ES6
- Importing specific D3 components
- Angular 6

**Reduced code snippet:** *Please have a look on drawPoints()*

```ts
import { ElementRef, HostListener, Output, EventEmitter, OnInit, Input, OnChanges, SimpleChanges, Directive } from '@angular/core';
import * as Selection from 'd3-selection';
import * as Shape from 'd3-shape';
import * as Random from 'd3-random';
import * as Drag from 'd3-drag';

import { Config } from './../models/config.model';
import { Point } from './../models/point.model';
import { Param } from './../models/param.model';

@Directive({
  selector: '[appCanvas]'
})
export class CanvasDirective implements OnInit, OnChanges {
  private canvas: any;
  private defs: any;
  private gradient: any;
  private svg: any;
  private expandedPoints: Point[];
  private drag: Point;
  public config: Config;

  @Input()
  private param: Param;

  @Output()
  private emitConfig: EventEmitter<Config>;

  @HostListener('window:resize', ['$event'])
  private onResize(event) {
    this.init();
  }

  constructor(
    private el: ElementRef
  ) {
    this.canvas = el.nativeElement;
    this.emitConfig = new EventEmitter();
  }

  ngOnInit() {
    intSvg();
    // ..
  }

  private initSvg() {
    if (!this.svg) {
      this.svg = Selection.select(this.canvas).append('svg');
    }
    this.svg
      .attr('width', this.config.width)
      .attr('height', this.config.height);
  }

  private drawPoints(points: Point[]) {
    points.forEach(point => {
      this.svg.append('circle')
        .attr('r', point.color ? 20 : 10)
        .attr('cx', point.x)
        .attr('cy', point.y)
        .attr('fill', point.color ? point.color : 'lightgray')
        .attr('stroke-width', !point.color ? 2 : 0)
        .attr('stroke', !point.color ? 'gray' : '')
        .call(Drag.drag()
          .on('drag', () => {
            // What to call here?
            // Selection.select(this) will not work
            // So how to target the correct „this“?
          }));
    });
  }
  // ...
}
```

The problem that occures is not beeing able to reach the correct `this` inside the drag function of the appended circles.

Multiple examples are out there, but they won't work inside the class, because the `this` argument is protected.

*Credits to Mike Bostock's example https://bl.ocks.org/mbostock/22994cc97fefaeede0d861e6815a847e*

**Comment by nextlevelshit** [comment]
By avoiding the popular arrow function syntax in ES6 components and using the good old `function() {}` syntax instead, the problem was solved. The arrow functions change the game, because within these called functions it turns out that `this` is not reduced to the called context of the function, but that the context extends globally till the class level.

**Solution:**
```js
private drawPoints(points: Point[]) {
  points.forEach(point => {
    this.svg.append('circle')
      .attr('r', point.color ? 20 : 10)
      .attr('cx', point.x)
      .attr('cy', point.y)
      .attr('fill', point.color ? point.color : 'lightgray')
      .attr('stroke-width', !point.color ? 2 : 0)
      .attr('stroke', !point.color ? 'gray' : '')
      .call(Drag.drag()
        .on('drag', function() {
          console.log(this);
        }));
  });
}
```

**Further reading:** 
> [...] and ES2015 [ES6] introduced arrow functions which don't provide their own this binding (it retains the this value of the enclosing lexical context).
[rwaldron, abasao, martian2049 et. al, *this*, MDN web docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this)

**Comment by arizzitano** [comment]
@nextlevelshit thank you so much for posting your solution and explanation here. You just saved me a ton of debugging time.
