### ISSUE TITLE
Possible typo in README

### ISSUE THREAD

**Issue by ondrejsevcik** [d3/d3-drag#55]
Hello,

this is from the README

```md
Internally, the drag behavior uses selection.on to bind the necessary event listeners for dragging. The listeners use the name .drag, so you can subsequently unbind the drag behavior as follows:

selection.on(".drag", null);  <--- should the event name contain dot? 
```

although I'm no expert on d3, this looks like a typo.

**Comment by mbostock** [comment]
This is not a typo. Please see the documentation for [selection.on](https://github.com/d3/d3-selection/blob/master/README.md#selection_on) and [*drag*](https://github.com/d3/d3-drag/blob/master/README.md#_drag) for explanation.
