### ISSUE TITLE
drag start event is don't send when Ctrl-key is press

### ISSUE THREAD

**Issue by freignat91** [d3/d3-drag#65]
Using d3-drag v1.2.3, when i click on a d3 object having d3.drag functions set, I well success to get start drag event when i click on the object with Ctrl-Key pressed.

Using d3-drag v1.2.4,with the same code, when I click on the same d3 object, i got the regular mouse-down event, not the drag start one.

I was using d3 v5.9.2 and all was ok. I moved to 5.12.0 and got the issue, but after analyze, this issue seems coming only from the version of the d3-drag.

**Comment by mbostock** [comment]
This is covered in the [release notes](https://github.com/d3/d3-drag/releases) and specifically the [linked issue](https://github.com/d3/d3-drag/issues/62#issuecomment-519194620).
