### ISSUE TITLE
d3.event is not available in version 6.1.1

### ISSUE THREAD

**Issue by borysl** [d3/d3-drag#76]
When I tried to create drag event the d3.event is always undefined. Finally I have dowgraded d3 to version 5 and it start working.

The example used was from here: https://bl.ocks.org/sistemawebpro/41d81ad70d7355691a61a6f7ac7f83d9

But I am using vue.js app and thus nmp start serve in order to see it.

What is wrong with version 6.1.1?

**Comment by Fil** [comment]
see https://github.com/d3/d3-drag/releases/tag/v2.0.0 & https://github.com/d3/d3/blob/master/CHANGES.md for the (recent) major changes to event management
