### ISSUE TITLE
DragEvent missing event.currentTarget for arrow function node selection

### ISSUE THREAD

**Issue by ChrisHSandN** [d3/d3-drag#77]
`d3.drag().subject()`, `d3.drag().on()` etc. used to be passed `datum, i, nodes` allowing the current node to be accessed from within an arrow function.

```js
// v5
d3
  .drag()
  .subject((datum, i, nodes) => {
    d3.select(nodes[i]);
  })
```

Now it has swapped to only the `DragEvent` object there doesn't seem to be any way to access the node anymore without using `this`?

```js
// v6
d3
  .drag()
  .subject((event) => {
    d3.select(???);
  })
```

d3.selection.on() has the [`event.currentTarget` ](https://github.com/d3/d3-selection/issues/263) which would be useful/consitent for `drag().*()`.

d3: v.6.2.0

**Comment by mbostock** [comment]
Try `event.sourceEvent.currentTarget`.
